In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, Flatten, Dropout 
from keras.models import Sequential, Model

In [2]:
model_cnn = Sequential([
    Conv2D(64, 3, input_shape=(128,128,1), use_bias=True ),
    MaxPooling2D(pool_size=4),
    Flatten(),
    Dropout(0.5),
    Dense(1, activation='softmax')
])

In [3]:
model_cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 64)      640       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 64)        0         
 D)                                                              
                                                                 
 flatten (Flatten)           (None, 61504)             0         
                                                                 
 dropout (Dropout)           (None, 61504)             0         
                                                                 
 dense (Dense)               (None, 1)                 61505     
                                                                 
Total params: 62145 (242.75 KB)
Trainable params: 62145 (242.75 KB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [4]:
model_cnn.save('simple_cnn.h5')

C:\Users\Marwah\anaconda3\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [5]:
input_shape = (4, 28, 28, 3)

In [6]:
x = tf.random.normal(input_shape)

In [7]:
x.shape

TensorShape([4, 28, 28, 3])

In [8]:
input_shape[1:]

(28, 28, 3)

In [9]:
y = Conv2D(2, 2, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 4, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, [3,2], activation='relu', input_shape=input_shape[1:])(x)


In [10]:
y.shape

TensorShape([4, 27, 27, 2])

In [11]:
y[0].shape

TensorShape([27, 27, 2])

In [12]:
z = MaxPooling2D(pool_size=3, strides=3)(y)

In [13]:
z.shape

TensorShape([4, 9, 9, 2])

In [14]:
z[0].shape

TensorShape([9, 9, 2])

In [15]:
ab = Flatten()(z)

In [16]:
ab.shape

TensorShape([4, 162])

In [17]:
ab[0].shape

TensorShape([162])

In [18]:
abz = Dropout(0.5,  noise_shape=None, seed=10)(ab)

In [19]:
abz.shape

TensorShape([4, 162])

In [20]:
abz[0]

<tf.Tensor: shape=(162,), dtype=float32, numpy=
array([1.7244483 , 2.1425734 , 0.8255292 , 0.6847329 , 1.6157376 ,
       1.1743103 , 1.0806444 , 1.0295231 , 1.147628  , 1.5067487 ,
       2.4450202 , 0.9559322 , 2.203899  , 1.5734937 , 1.9353607 ,
       1.7929082 , 1.83198   , 1.4720557 , 1.4369    , 1.4159908 ,
       1.64661   , 2.212461  , 2.2257295 , 2.3529732 , 2.305692  ,
       1.5303214 , 2.9319313 , 0.7638989 , 1.5878749 , 1.271449  ,
       1.9543461 , 0.38219142, 1.8911839 , 0.9412107 , 0.88735867,
       1.8851857 , 1.0306219 , 1.6922317 , 2.1604505 , 1.4437292 ,
       1.7579298 , 2.2413142 , 1.6698768 , 2.3329158 , 1.0009099 ,
       2.2737396 , 1.8198942 , 1.0883857 , 1.7716792 , 1.7792026 ,
       1.6031277 , 0.79042614, 1.4852654 , 1.0079398 , 1.972682  ,
       1.3372201 , 2.7207217 , 0.23011471, 2.6991405 , 0.7541826 ,
       2.3953433 , 0.8661539 , 1.371603  , 1.66512   , 1.6095507 ,
       1.2169406 , 1.9178908 , 0.9470654 , 0.9932388 , 0.6834241 ,
       1.46855

In [21]:
final = Dense(10, activation='softmax')(abz)

In [22]:
final

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1.1878023e-02, 7.2768682e-01, 3.2785356e-03, 2.0109996e-01,
        3.4305602e-02, 1.7453725e-03, 5.6842538e-03, 4.0512048e-03,
        6.0908422e-03, 4.1793953e-03],
       [9.3986411e-03, 3.3817092e-01, 9.1585219e-03, 4.4268632e-01,
        7.3116742e-02, 7.1849935e-03, 5.2348547e-02, 5.7526017e-03,
        1.1224801e-02, 5.0957981e-02],
       [1.0632711e-02, 7.6564544e-01, 1.1021536e-02, 1.6585870e-01,
        1.7009642e-02, 1.9153424e-03, 3.7175217e-03, 5.4049115e-03,
        5.3474219e-03, 1.3446737e-02],
       [4.6136826e-03, 1.5716401e-01, 8.5352771e-03, 7.5304633e-01,
        5.6324247e-02, 4.1802222e-04, 7.4872351e-03, 5.6548296e-03,
        7.7061279e-04, 5.9857881e-03]], dtype=float32)>

In [23]:
final_relu = Dense(10, activation='relu')(abz)

In [24]:
final_relu

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.        , 0.        , 2.2831926 , 0.        , 0.        ,
        0.08356649, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.2468666 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.95625037, 0.        , 0.72283864, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.04564614, 0.        , 1.7439635 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]],
      dtype=float32)>