Concatenate two arrays arr1 and arr2 horizontally (side by side) using np.concatenate().

In [5]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

concatenated_arr = np.concatenate((arr1, arr2), axis=1)

print(concatenated_arr)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Concatenate two arrays arr1 and arr2 vertically (stacked on top of each other) using
np.concatenate().

In [7]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

concatenated_arr = np.concatenate((arr1, arr2), axis=0)

print(concatenated_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Create to series s1:(1,2,3) s2:(4,5,6) and concatenate them horizontally (side by side) using
pd.concat().

In [9]:
import pandas as pd

s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

concatenated_series = pd.concat([s1, s2], axis=1)

print(concatenated_series)

   0  1
0  1  4
1  2  5
2  3  6


Concatenate two series s1 and s2 vertically (stacked on top of each other) using pd.concat()

In [10]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

concatenated_series = pd.concat([s1, s2], axis=0)

print(concatenated_series)

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


Create two data frames df1: {'A': [1, 2, 3], 'B': [4, 5, 6]}, df2: {'C': [7, 8, 9], 'D': [10, 11, 12]} and
concatenate them horizontally (side by side) using pd.concat().

In [11]:
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data1)

data2 = {'C': [7, 8, 9], 'D': [10, 11, 12]}
df2 = pd.DataFrame(data2)

concatenated_df = pd.concat([df1, df2], axis=1)

print(concatenated_df)

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12


Concatenate two data frames df1 and df2 vertically (stacked on top of each other) using
pd.concat()

In [12]:
concatenated_df = pd.concat([df1, df2], axis=0)

print(concatenated_df)

     A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0


 Concatenate two data frames df1 and df2 horizontally (side by side) using df1.join(df2).

In [13]:
concatenated_df = df1.join(df2)

print(concatenated_df)

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12


Concatenate two data frames df1 and df2 vertically (stacked on top of each other) using
df1.append(df2)

In [14]:
concatenated_df = df1.append(df2)

print(concatenated_df)

     A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0


C:\Users\user\AppData\Local\Temp\ipykernel_3076\1674703451.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  concatenated_df = df1.append(df2)


Concatenate two data frames df1 and df2 vertically (stacked on top of each other) and reset the
index using pd.concat() and the argument ignore_index=True.

In [15]:
concatenated_df = pd.concat([df1, df2], ignore_index=True)

print(concatenated_df)

     A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
3  NaN  NaN  7.0  10.0
4  NaN  NaN  8.0  11.0
5  NaN  NaN  9.0  12.0


Concatenate two data frames df1 and df2 vertically (stacked on top of each other) and add a
multi-level index using pd.concat() and the argument keys=['df1', 'df2'].

In [16]:
concatenated_df = pd.concat([df1, df2], keys=['df1', 'df2'])

print(concatenated_df)

         A    B    C     D
df1 0  1.0  4.0  NaN   NaN
    1  2.0  5.0  NaN   NaN
    2  3.0  6.0  NaN   NaN
df2 0  NaN  NaN  7.0  10.0
    1  NaN  NaN  8.0  11.0
    2  NaN  NaN  9.0  12.0
