In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Sample data
X = np.array([140, 150, 160, 170, 180]).reshape(-1, 1)  # Height
y = np.array([7, 8, 9, 10, 11])                        # Shoe size

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict shoe size for a given height
new_height = np.array([[155], [175]])  # New heights for prediction
predicted_shoe_sizes = model.predict(new_height)

print(predicted_shoe_sizes)


[ 8.5 10.5]


In [1]:
import numpy as np

In [2]:
 l1=[1,2,3,4] 

In [3]:
l1

[1, 2, 3, 4]

In [5]:
arry1=np.array(l1) 

In [6]:
arry1

array([1, 2, 3, 4])

In [7]:
l2=[11,22,33,44] #another list
l2

[11, 22, 33, 44]

In [8]:
l=[l1,l2] #combining two lists
l 

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
array_2D=np.array(l) #2D array

In [10]:
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
array_2D.shape 

(2, 4)

In [12]:
array_2D.dtype 

dtype('int32')

In [13]:
np.zeros(3,'int') 

array([0, 0, 0])

In [14]:
np.ones(3) 

array([1., 1., 1.])

In [15]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros(3)
np.empty(3)

array([0., 0., 0.])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [33]:
#qustions1:

l2=[0,1,2,3,4]
l2

[0, 1, 2, 3, 4]

In [34]:
l3=[5,6,7,8,9]
l3

[5, 6, 7, 8, 9]

In [35]:
L=[l2,l3]
L

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [36]:
array_2D=np.array(L) 

In [37]:
array_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
array_2D.shape 

(2, 5)

In [39]:
#Qustion2:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#Qustion_3:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
#Qustion_4:
np.random.randint(0,100,10)

array([44, 52, 67,  4, 26, 64, 44, 88, 41, 61])

In [50]:
np.random.rand(0,1,10)

array([], shape=(0, 1, 10), dtype=float64)

In [51]:
#Qustion_5:
np.random.rand(10)

array([0.48659783, 0.76608879, 0.76926025, 0.80785284, 0.13091529,
       0.6636418 , 0.83704991, 0.78053101, 0.5380543 , 0.59650306])

In [60]:
#Qustion_6:
# numpay arry 5 equally spaced between 0 and 1
import numpy as np

arr3 = np.linspace(0, 1, 5)


In [61]:
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
#Qustion_7:
# numpay arry 5 equally spaced between 0 and 10
import numpy as np

arr = np.linspace(0, 10, 5)


In [53]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
#Qustion_8:
# numpay arry 5 equally spaced between -1 and 1
import numpy as np
arr1 = np.linspace(-1, 1, 5)



In [56]:
arr1

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [67]:
#Qustion_9:
# numpy sine value of angles between 0 and 2 PI

angles = np.linspace(0, 2*np.pi, 100)  # Adjust the number of points (100 in this case)

# Calculate the sine values
sine_values = np.sin(angles)


In [68]:
sine_values

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [69]:
#Qustion_10:
# numpy cosine value of angles between 0 and PI
import numpy as np

angles = np.linspace(0, np.pi, 100)
cosine_values = np.cos(angles)

In [70]:
cosine_values

array([ 1.        ,  0.99949654,  0.99798668,  0.99547192,  0.99195481,
        0.98743889,  0.9819287 ,  0.97542979,  0.9679487 ,  0.95949297,
        0.95007112,  0.93969262,  0.92836793,  0.91610846,  0.90292654,
        0.88883545,  0.87384938,  0.85798341,  0.84125353,  0.82367658,
        0.80527026,  0.78605309,  0.76604444,  0.74526445,  0.72373404,
        0.70147489,  0.67850941,  0.65486073,  0.63055267,  0.60560969,
        0.58005691,  0.55392006,  0.52722547,  0.5       ,  0.47227107,
        0.44406661,  0.41541501,  0.38634513,  0.35688622,  0.32706796,
        0.29692038,  0.26647381,  0.23575894,  0.20480667,  0.17364818,
        0.14231484,  0.1108382 ,  0.07924996,  0.04758192,  0.01586596,
       -0.01586596, -0.04758192, -0.07924996, -0.1108382 , -0.14231484,
       -0.17364818, -0.20480667, -0.23575894, -0.26647381, -0.29692038,
       -0.32706796, -0.35688622, -0.38634513, -0.41541501, -0.44406661,
       -0.47227107, -0.5       , -0.52722547, -0.55392006, -0.58

In [75]:
# create 2*2 array and multibite by 2 

array2 = np.array([[1, 2], [3, 4]])

# Multiply the array by 2
arr = array2 * 2


In [76]:
arr

array([[2, 4],
       [6, 8]])

In [77]:
# create 3*3 and add 5 in each element 

array3 = np.array([[1, 2,3], [4,5,6]])

# add the array to 5
arr1 = array3 + 5

In [78]:
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
# create 4 *4 and sub by 10

array4 = np.array([[1, 2,3 ,4], [5,6,7,8]])

# sub the array to 10
arr1 = array4 - 10

In [80]:
arr1

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2]])

In [81]:
#create 5 * 5 div by 2

array5 = np.array([[1, 2,3 ,4, 5], [6,7,8, 9 ,10]])

# div the array to 2
arr1 = array5 / 2


In [82]:
arr1

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ]])

In [83]:
# create 6 * 6 and sqr each elements 
array6 = np.array([[1, 2,3 ,4, 5,6], [7,8, 9 ,10,11,12]])

# sqrt the array 
arr1 = np.sqrt(array6)

In [84]:
arr1

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162]])

In [88]:
# create 2*2 and calculate np.matmul() function 

array7 = np.array([[1, 2],[3, 4]])
array8 = np.array([[5, 6],[7, 8]])
arr1 = np.matmul(array7,array8)

In [89]:
arr1

array([[19, 22],
       [43, 50]])

In [91]:
# create tow 3*3 np.dot()
array7 = np.array([[1, 2,3],[4,5,6],[7,8,9]])
array8 = np.array([[10,11,12],[13,14,15],[16,17,18]])
arr1 = np.dot(array7,array8)

In [92]:
arr1

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [93]:
# create 2*3 and 3*2 and calculate np.matmul()
array7 = np.array([[1, 2,5],[3, 4,6]])
array8 = np.array([[10,11],[13,14],[16,17]])
arr1 = np.matmul(array7,array8)

In [94]:
arr1

array([[116, 124],
       [178, 191]])

In [95]:
# create 2*3 and 3*2 and calculate np.dot()
array7 = np.array([[1, 2,5],[3, 4,6]])
array8 = np.array([[10,11],[13,14],[16,17]])
arr1 = np.dot(array7,array8)

In [96]:
arr1

array([[116, 124],
       [178, 191]])

In [97]:
# 1. Create a 1D NumPy array with the integers from 0 to 9. Extract the 3rd element from the array.

arr = np.arange(10)

third_element = arr[2]


In [98]:
third_element

2

In [108]:
#2. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Extract the element at row 2, column 1.

random_array = np.random.rand(3, 3)

element1_2 = random_array[1][0]


In [109]:
random_array

element1_2

0.02834905389730691

In [102]:
# 3.Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarrayconsisting of the first 2 rows and the last 2 columns.

random_array = np.random.rand(4, 4)

sub_array = random_array[:2, -2:]


In [103]:
random_array
sub_array


array([[0.05719945, 0.85200722],
       [0.9440782 , 0.56098344]])

In [111]:
#4.Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the first 3 elements.

original_array = np.arange(10)

slice_array = original_array[:3].copy()


In [112]:
original_array
slice_array

array([0, 1, 2])

In [113]:
#5. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of thearray consisting of the first 2 rows and the first 2 columns.


array = np.random.rand(3, 3)
array
slice_array = array[:2, :2]


In [114]:
slice_array

array([[0.91843273, 0.1632771 ],
       [0.69733956, 0.01698354]])

In [122]:
# 6. Create a 1D NumPy array with the integers from 0 to 9. Reshape the array into a 2D array withshape (3, 3).


arr_1d = np.arange(9)

arr_2d = arr_1d.reshape(3, 3)

In [123]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
# 7. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array into a 1D array.

random_2d = np.random.rand(4, 4)


In [127]:
random_2d

array([[0.18367571, 0.27652273, 0.47833594, 0.32396468],
       [0.35815777, 0.14754626, 0.51623863, 0.82805612],
       [0.13801651, 0.79418356, 0.96112051, 0.10840496],
       [0.95717869, 0.83923368, 0.88191707, 0.54676711]])

In [128]:
reshaped_array = random_2d.flatten()
reshaped_array

array([0.18367571, 0.27652273, 0.47833594, 0.32396468, 0.35815777,
       0.14754626, 0.51623863, 0.82805612, 0.13801651, 0.79418356,
       0.96112051, 0.10840496, 0.95717869, 0.83923368, 0.88191707,
       0.54676711])

In [129]:
# 8. Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into asingle 1D array.

array1 = np.array([0, 1, 2, 3, 4])
array2 = np.array([0, 1, 2, 3, 4])
result_array = np.concatenate((array1, array2))

In [130]:
array1
array2
result_array

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [131]:
# 9. Create two 2D NumPy arrays with shapes (2, 2) and (2, 3). Concatenate the two arrayshorizontally
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6, 7],
                   [8, 9, 10]])
concatenated_array = np.hstack((array1, array2))

In [132]:
array1
array2
concatenated_array

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [147]:
# 10.Create two 2D NumPy arrays with shapes (2, 2) and (3, 2). Concatenate the two arrays vertically.




In [148]:
array = np.random.rand(5, 5)
array


array([[0.45891977, 0.52440436, 0.26840326, 0.84679207, 0.60853488],
       [0.49861142, 0.88119274, 0.36436357, 0.69414648, 0.97562679],
       [0.14633553, 0.86457203, 0.06306195, 0.55225585, 0.36823939],
       [0.5586207 , 0.455567  , 0.20705491, 0.13193747, 0.14841875],
       [0.86068361, 0.23911354, 0.25928724, 0.9319955 , 0.10455528]])

In [149]:
2+1.5*array

array([[2.68837965, 2.78660654, 2.40260489, 3.27018811, 2.91280232],
       [2.74791714, 3.32178912, 2.54654536, 3.04121972, 3.46344018],
       [2.21950329, 3.29685805, 2.09459292, 2.82838377, 2.55235908],
       [2.83793105, 2.6833505 , 2.31058236, 2.1979062 , 2.22262812],
       [3.29102541, 2.3586703 , 2.38893086, 3.39799324, 2.15683292]])

In [150]:
A=np.array([-2,5,4,-8,0])
print(np.sort(A))
print(- np.sort(A))
print(np.flip(np.sort(A)))

[-8 -2  0  4  5]
[ 8  2  0 -4 -5]
[ 5  4  0 -2 -8]


In [153]:
#Lets learn about unique
countries = np.array(['France', 'Germany', 'USA','Russia','USA','Mexico','Germany'])
np.unique(countries)


array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [154]:
#Test for membership
# in1d test values in one array
np.in1d(['France','USA','Sweden'],countries)

array([ True,  True, False])