In [3]:
# Create two 2D NumPy arrays with shapes (2, 2) and (3, 2). Concatenate the two arrays vertically.
import numpy as np

array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8],
                   [9, 10]])
concatenated_array = np.vstack((array1, array2))


In [5]:
print(concatenated_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [20]:
#1.Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp()
#function to compute the exponential of each element in the array

arr= np.random.rand(3,3)
exp_array = np.exp(arr)

print("Array:")
print(arr)

print("Exponential Array: ")
print(exp_array)


Array:
[[0.59076886 0.76639177 0.6082561 ]
 [0.70512866 0.61459591 0.41346588]
 [0.21788146 0.73155045 0.01496554]]
Exponential Array: 
[[1.80537597 2.15198736 1.83722466]
 [2.02410709 1.84890933 1.5120493 ]
 [1.24343966 2.07830041 1.01507808]]


In [21]:
#2.Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function
#to compute the sine of each element in the array.

arr = np.random.rand(4, 4)
sin_arr = np.sin(arr)

print("Array:")
print(arr)

print("sin array")
print(sin_arr)


Random array:
[[0.68668193 0.96807708 0.31805179 0.29662496]
 [0.68967514 0.31278884 0.41582309 0.83329971]
 [0.46211795 0.62711072 0.89853671 0.41371128]
 [0.91762807 0.06196786 0.88080317 0.64056004]]
sin array
[[0.63397464 0.82379716 0.31271665 0.29229424]
 [0.6362866  0.30771335 0.40394302 0.74015425]
 [0.4458449  0.58680769 0.78241648 0.40201027]
 [0.79416242 0.06192821 0.77125037 0.59764455]]


In [22]:
#3.Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log()
#function to compute the natural logarithm of each element in the array.

arr = np.random.rand(5, 5)
log_arr = np.log(arr)

print("Array:")
print(random_array)

print("natural logarithm:")
print(log_arr)


Random array:
[[0.14643449 0.82664972 0.80750378 0.42808248]
 [0.18771151 0.70935924 0.32257433 0.61920466]
 [0.89802508 0.21486896 0.25274175 0.38839743]
 [0.08399467 0.50228288 0.74181427 0.00318409]]
natural logarithm:
[[-0.54438738 -0.25006066 -1.48708444 -1.30483487 -1.52997709]
 [-0.20271562 -1.2150461  -2.75262571 -0.35064061 -0.36039683]
 [-0.10920077 -1.75519254 -0.31836675 -0.92158417 -1.51388353]
 [-0.20114787 -0.63883549 -1.03094842 -1.34128416 -0.50962703]
 [-0.75689035 -5.32336902 -0.66015852 -0.10103838 -0.91519324]]


In [10]:
#4.Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt()
#function to compute the square root of each element in the array.

arr = np.random.rand(2, 2)
sqrt_arr = np.sqrt(arr)

print("Array:")
print(arr)

print("Square Array:")
print(sqrt_arr)


Random Array:
[[0.54256934 0.68182084]
 [0.79138612 0.35387596]]

Square Root of Random Array:
[[0.73659306 0.82572443]
 [0.88959886 0.59487475]]


In [23]:
#5.Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor()
#function to round down each element in the array to the nearest integer.

arr = np.random.rand(6, 6)
round_arr = np.floor(arr)

print(round_arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [26]:
#6.Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs()
#function to compute the absolute value of each element in the array.

arr = np.random.rand(3, 3) * 2 - 1
absolute_array = np.abs(arr)

print(absolute_array)


[[0.84290795 0.85077225 0.75779361]
 [0.61766311 0.00288398 0.21949769]
 [0.484541   0.99793091 0.65584536]]


In [27]:
#7.Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power()
#function to raise each element in the array to the power of 2

arr = np.random.rand(4, 4)
result_array = np.power(arr, 2)

print(result_array)


[[0.46699918 0.06935133 0.72402182 0.77708575]
 [0.54279609 0.35962776 0.91857271 0.36930716]
 [0.22779966 0.42551198 0.03951862 0.75862104]
 [0.20025554 0.01570522 0.44240568 0.15125133]]


In [28]:
#8.Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to
#find the largest element in the array.

arr_int = np.random.randint(1, 11, 5)
largest_value = np.max(arr_int)

print(arr_int)
print("Largest element:", largest_value)


[ 5  7 10  7  1]
Largest element: 10


In [29]:
#9.Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round
#function to round each element to the nearest integer.

arr_float = np.random.rand(10)
round_int = np.round(arr_float)

print("random float array with rade 10: ")
print(arr_float)

print("rondom intger array: ")
print(round_int)


random float array with rade 10
[0.44372987 0.20571204 0.81030381 0.47039121 0.18052501 0.9223123
 0.52083779 0.22068217 0.64487293 0.78283648]
rondom intger array
[0. 0. 1. 0. 0. 1. 1. 0. 1. 1.]


In [32]:
#10. Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to
#find the index of the largest element in the array.

arr_int = np.random.randint(1, 101, size=7)

print("array between 1 and 100: ")
print(arr_int)

largest_index= np.argmax(arr_int)

print("largest elementas index :")
print(largest_index)
print("Largest element:", random_integers[index_of_largest])


array between 1 and 100: 
[34 44  6 31 54 97 40]
largest elementas index :
5
Largest element: 94


In [34]:
#11. Create two NumPy arrays with the same shape, each filled with random integers between 1 and
#10. Use the add function to add the two arrays together element-wise.
np.random.seed(42)

array1 = np.random.randint(1, 11, size=(3, 3))  
array2 = np.random.randint(1, 11, size=(3, 3))

result_array = np.add(array1, array2)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult after element-wise addition:")
print(result_array)


Array 1:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Array 2:
[[5 4 8]
 [8 3 6]
 [5 2 8]]

Result after element-wise addition:
[[12  8 16]
 [13 10 16]
 [ 8  9 16]]


In [33]:
#12.Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit
#the values in the array to a range between 10 and 90.
arr_int= np.random.randint(0,101, size=12)

clipped_arr=np.clip(arr_int, 10, 90)

print (" random number intger: ", arr_int)
print ("clipped_array: ", clipped_arr)


 random number intger:  [15  2 61 92  2 98 70 44 60 82 46 27]
clipped_array:  [15 10 61 90 10 90 70 44 60 82 46 27]
