In [2]:
#1. Create a NumPy array with 10 random integers between 0 and 100

import numpy as np
random_integers = np.random.randint(0, 101, 10)
print(random_integers)


[65 85 79 82 75 79 38 53 57 24]


In [4]:
# 2. Use the np.where() function to create a new array with the same shape as the previous one,
# where values less than 50 are replaced with -1 and values greater than or equal to 50 are
# replaced with 1

import numpy as np
a = np.array([20, 30, 40, 50, 60, 70, 80, 90])
new_array = np.where(a < 50, -1, 1)

print(new_array)


[-1 -1 -1  1  1  1  1  1]


In [5]:
#3. Calculate the mean, median, and standard deviation of the original array.
np.mean(random_integers)

63.7

In [7]:
np.median(random_integers)

70.0

In [8]:
np.std(random_integers)

19.44762196259481

In [9]:
# Create a boolean array that is True where the values in the original array are even, and False
# otherwise.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
boolean_array = arr % 2 == 0

print(boolean_array)



[False  True False  True False  True False  True False  True]


In [11]:
#5. Sort the original array in ascending order
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr.sort()

print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#6. Find the unique values in the original array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.unique(arr))

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
#7. Use the np.in1d() function to create a boolean array indicating which elements of the original
# array are also present in a new array with 5 random integers between 0 and 100.

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
random_array = np.random.randint(0, 100, 5)
boolean_array = np.in1d(arr, random_array)
print("Original Array:", arr)
print("New Random Array:", random_array)
print("Boolean Array:", boolean_array)


Original Array: [10 20 30 40 50 60 70 80 90]
New Random Array: [75  1 88 94 57]
Boolean Array: [False False False False False False False False False]


In [18]:
#8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.savetxt("my_array.txt", arr)
